services:
  web:
    build: .
    container_name: reporting_erp_app
    ports:
<<<<<<< HEAD
      - "9001:8900"
=======
      - "4000:8900"
>>>>>>> 08dda58 (feat: Redesign user detail page with charts and an enhanced report table, add comprehensive documentation, and update Docker configurations.)
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: reporting_erp_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
