# Generated by Django 5.2.6 on 2025-10-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
