# Generated by Django 5.2.6 on 2025-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="shift",
            field=models.CharField(
                choices=[
                    ("7_3_30", "7:00 AM – 3:30 PM"),
                    ("8_8_30", "8:00 AM – 8:30 PM"),
                    ("9_5_30", "9:00 AM – 5:30 PM"),
                    ("10_6_30", "10:00 AM – 6:30 PM"),
                    ("12_8_30", "12:00 PM – 8:30 PM"),
                    ("2_30_11", "2:30 PM – 11:00 PM"),
                    ("wfh", "Work From Home"),
                ],
                default="9_5_30",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="custom_date",
            field=models.DateField(
                blank=True, help_text="The date this report is for", null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateField(auto_now_add=True, help_text="Auto submission date"),
        ),
    ]
