# Generated by Django 5.0.6 on 2025-11-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_dynamicfield_dynamicfieldresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='team',
            field=models.CharField(choices=[('content_writer', 'Content Writer'), ('graphic_designer', 'Graphic Designer'), ('video_editor', 'Video Editor'), ('social_media', 'Social Media')], max_length=100),
        ),
    ]
