# Generated by Django 5.0.6 on 2025-11-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_dynamicfield_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anchor_presenter_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='interview_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='live_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='logo_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='presenter_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reel_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='special_work_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='vo_video',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicfield',
            name='team',
            field=models.CharField(choices=[('content_writer', 'Content Writer'), ('graphic_designer', 'Graphic Designer'), ('video_editor', 'Video Editor'), ('social_media', 'Social Media'), ('video_producer', 'Video Producer'), ('reporter', 'Reporter'), ('cameraman', 'Cameraman'), ('marketing', 'Marketing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='tasks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('content_writer', 'Content Writer'), ('graphic_designer', 'Graphic Designer'), ('video_editor', 'Video Editor'), ('social_media', 'Social Media'), ('video_producer', 'Video Producer'), ('reporter', 'Reporter'), ('cameraman', 'Cameraman'), ('marketing', 'Marketing')], max_length=50),
        ),
    ]
