# Generated by Django 5.0.6 on 2025-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_anchor_presenter_video_report_interview_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='shift',
            field=models.CharField(choices=[('7_3_30', '7:00 AM – 3:30 PM'), ('8_8_30', '8:00 AM – 4:30 PM'), ('9_5_30', '9:00 AM – 5:30 PM'), ('10_6_30', '10:00 AM – 6:30 PM'), ('12_8_30', '12:00 PM – 8:30 PM'), ('2_30_11', '2:30 PM – 11:00 PM'), ('wfh', 'Work From Home')], default='9_5_30', max_length=20),
        ),
    ]
