# Generated by Django 5.0.6 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('regular', 'Regular Working Day'), ('leave', 'On Leave')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_off',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6),
        ),
    ]
